name: Build GBFS Snapshot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run snapshot builder
        run: node build_snapshot.mjs

      - name: Commit snapshot
        run: |
          git config user.name "gh-pages bot"
          git config user.email "bot@users.noreply.github.com"
          git add snapshot.json history.json
          git commit -m "Update snapshot [skip ci]" || echo "No changes"
          git push
